=head1 NAME

Unco - undo any command

=head1 SYNOPSIS

 # record changes to files made by cmd
 % unco record -- cmd args

 # display a list of recorded commands
 % unco history

 # undo a recorded change
 % unco undo <index>

 # redo a recorded change
 % undo redo <index>

=head1 DESCRIPTION

Unco is a wrapper program that records the changes made to files by programs so
that they can be undone laterwards.

It uses a technique called library preloading (for more information consult the
linux documents with keyword LD_PROLOAD, or os x document with keyword
DYLD_INSERT_LIBRARIES) to trap the library calls that affect the files, and
records the changes made by the programs being executed.

=head1 INSTALLATION

 cmake .
 make
 make install

=head1 SUB-COMMANDS

=head2 unco record

 % unco record [--log=<path>] [--append] -- cmd args

The command executes given command while logging the changes.

=head3 --log=<path>

specifies the location of the log (if omitted, the log is stored under
$HOME/.unco with appropriate index)

=head3 --append

used together with --log for appending the changes to the log (default
behavior is truncate)

=head2 unco history

 % unco history

Displays the list of recorded commands with their associated indices.

=head2 unco undo

 % unco undo [--print] <index>

Undoes a recorded change.  The index is the number displayed by
L</unco history>.

=head3 --print

displays the changes to be performed instead of actually applying them

=head2 unco redo

 % unco redo [--print] <index>

Redoes a recorded change that has been undone.  The index is the number
displayed by L</unco history>.

=head1 AUTHOR

Kazuho Oku

=head1 LICENSE

MIT

=cut

